"""The home insurance quote intake, expressed entirely as data.

Wording lives here rather than in the agent's prompt for one reason: an intake question is a
compliance artefact. It gets reviewed, it gets changed by people who do not read Python, and the
version that was asked has to be recoverable from the record of a call. A question buried in a system
prompt satisfies none of that.
"""

from __future__ import annotations

from form_spec import (
    AnswerType,
    Condition,
    Field,
    Questionnaire,
    RepeatGroup,
    Section,
)

LICENSED_STATES = (
    "AZ", "CO", "GA", "IL", "IN", "KY", "MI", "NC", "OH", "PA", "SC", "TN", "TX", "VA", "WI",
)

# Breeds a carrier panel commonly declines on. Kept as data because the list is a business input that
# changes without the software changing.
RESTRICTED_DOG_BREEDS = (
    "pit bull", "rottweiler", "doberman", "chow chow", "presa canario", "wolf hybrid",
    "akita", "cane corso",
)

SECTIONS = (
    Section(
        "identity_consent",
        "Identity and consent",
        "Before anything else I have to check I am speaking to the right person and that you are happy to continue.",
    ),
    Section(
        "property",
        "The property",
        "Let me start with the home itself.",
    ),
    Section(
        "roof_systems",
        "Roof and systems",
        "Now the roof and the systems in the house, which is what carriers ask about most.",
    ),
    Section(
        "protective_risk",
        "Protective and risk features",
        "A few things about safety features and what else is on the property.",
    ),
    Section(
        "coverage_policy",
        "Coverage and current policy",
        "Next, what you have in place today.",
    ),
    Section(
        "loss_history",
        "Loss history",
        "I need to ask about past claims. It affects which carriers can look at this.",
    ),
    Section(
        "auto_bundle",
        "Auto bundle",
        "Many people save more by putting the car on the same policy, so let me ask.",
    ),
    Section(
        "disposition",
        "Next steps",
        "Nearly done. Just how you would like to take this forward.",
    ),
)

REPEAT_GROUPS = (
    RepeatGroup("claims", "claims_count", maximum=5, label_singular="claim"),
    RepeatGroup("vehicles", "vehicle_count", maximum=4, label_singular="vehicle"),
    RepeatGroup("drivers", "driver_count", maximum=4, label_singular="driver"),
)

_IDENTITY = (
    Field(
        "reached_right_party",
        "identity_consent",
        "Am I speaking with the homeowner?",
        AnswerType.ENUM,
        reprompts=("Are you the owner of the property, or someone else in the household?",),
        choices=("homeowner", "co_owner", "authorised_other", "not_available", "wrong_number"),
        synonyms=(
            ("speaking", "homeowner"), ("that is me", "homeowner"), ("that's me", "homeowner"),
            ("this is she", "homeowner"), ("this is he", "homeowner"), ("i own", "homeowner"),
            ("my husband", "co_owner"), ("my wife", "co_owner"), ("we own", "co_owner"),
            ("power of attorney", "authorised_other"), ("on their behalf", "authorised_other"),
            ("not here", "not_available"), ("at work", "not_available"),
            ("wrong number", "wrong_number"), ("no one by that name", "wrong_number"),
        ),
        required_for_quote=True,
    ),
    Field(
        "homeowner_confirmed",
        "identity_consent",
        "And you own the home rather than rent it?",
        AnswerType.BOOL,
        reprompts=("Just to confirm, is the property yours rather than rented?",),
        required_for_quote=True,
        fatal_if_refused=True,
        feeds_rules=("renter_not_homeowner",),
    ),
    Field(
        "recording_disclosure_ack",
        "identity_consent",
        "This call is recorded for quality and training. Is that alright with you?",
        AnswerType.BOOL,
        required_for_quote=True,
        fatal_if_refused=True,
    ),
    Field(
        "consent_to_continue",
        "identity_consent",
        "Your lender passed your details across so we could shop your home insurance. Have you got a few minutes to go through it?",
        AnswerType.BOOL,
        reprompts=("Is now a reasonable time, or should I call back?",),
        required_for_quote=True,
        fatal_if_refused=True,
    ),
    Field(
        "contact_name",
        "identity_consent",
        "Can I take your full name as it should appear on the policy?",
        AnswerType.STRING,
        required_for_quote=True,
    ),
    Field(
        "preferred_language",
        "identity_consent",
        "Would you rather carry on in English or Spanish?",
        AnswerType.ENUM,
        choices=("english", "spanish", "other"),
    ),
    Field(
        "callback_number_confirm",
        "identity_consent",
        "Is this the best number to reach you on?",
        AnswerType.PHONE,
    ),
)

_PROPERTY = (
    Field(
        "property_address",
        "property",
        "What is the full address of the home we are insuring?",
        AnswerType.ADDRESS,
        reprompts=("Could I get the street, city and zip for the property?",),
        required_for_quote=True,
        fatal_if_refused=True,
    ),
    Field(
        "property_state",
        "property",
        "And which state is that in?",
        AnswerType.STRING,
        required_for_quote=True,
        feeds_rules=("outside_licensed_states",),
    ),
    Field(
        "mailing_same_as_property",
        "property",
        "Is your mail sent to that same address?",
        AnswerType.BOOL,
    ),
    Field(
        "mailing_address",
        "property",
        "What address should the paperwork go to instead?",
        AnswerType.ADDRESS,
        asked_when=Condition("mailing_same_as_property", "eq", False),
    ),
    Field(
        "occupancy",
        "property",
        "Is that your main home, a second home, a rental, or is it sitting empty?",
        AnswerType.ENUM,
        choices=("primary", "secondary", "rental", "vacant"),
        synonyms=(
            ("where we live", "primary"), ("main home", "primary"), ("main residence", "primary"),
            ("we live there", "primary"), ("live in it", "primary"), ("our home", "primary"),
            ("second home", "secondary"), ("holiday home", "secondary"), ("vacation", "secondary"),
            ("let out", "rental"), ("tenants", "rental"), ("rent it out", "rental"),
            ("rented out", "rental"), ("investment property", "rental"),
            ("empty", "vacant"), ("nobody lives", "vacant"), ("unoccupied", "vacant"),
            ("standing empty", "vacant"),
        ),
        required_for_quote=True,
        feeds_rules=("vacant_property", "vacant_long_term"),
    ),
    Field(
        "vacant_since_months",
        "property",
        "Roughly how many months has it been empty?",
        AnswerType.INT,
        minimum=0,
        maximum=600,
        asked_when=Condition("occupancy", "eq", "vacant"),
        feeds_rules=("vacant_long_term",),
    ),
    Field(
        "rental_months_per_year",
        "property",
        "How many months of the year is it let out?",
        AnswerType.INT,
        minimum=0,
        maximum=12,
        asked_when=Condition("occupancy", "eq", "rental"),
    ),
    Field(
        "rental_short_term_platform",
        "property",
        "Is it let short term through a booking site, or on a longer lease?",
        AnswerType.BOOL,
        asked_when=Condition("occupancy", "eq", "rental"),
        feeds_rules=("short_term_rental",),
    ),
    Field(
        "year_built",
        "property",
        "What year was the house built?",
        AnswerType.YEAR,
        reprompts=("Roughly what year did it go up? An approximate decade is fine.",),
        required_for_quote=True,
        minimum=1700,
        maximum=2030,
        feeds_rules=("old_home_no_updates",),
    ),
    Field(
        "square_feet",
        "property",
        "About how many square feet is the living space, not counting the garage?",
        AnswerType.INT,
        minimum=200,
        maximum=25000,
        required_for_quote=True,
    ),
    Field(
        "construction_type",
        "property",
        "Is it timber frame, masonry, brick veneer, or something else?",
        AnswerType.ENUM,
        choices=("frame", "masonry", "brick_veneer", "stucco", "log", "other"),
        synonyms=(
            ("timber", "frame"), ("wood frame", "frame"), ("wooden", "frame"),
            ("solid brick", "masonry"), ("block", "masonry"), ("concrete", "masonry"),
            ("brick", "brick_veneer"), ("brick front", "brick_veneer"),
            ("render", "stucco"), ("log cabin", "log"),
        ),
        required_for_quote=True,
    ),
    Field(
        "storeys",
        "property",
        "How many storeys?",
        AnswerType.INT,
        minimum=1,
        maximum=6,
    ),
    Field(
        "foundation_type",
        "property",
        "Does it sit on a basement, a crawl space, or a slab?",
        AnswerType.ENUM,
        choices=("basement", "crawl_space", "slab", "pier_and_beam"),
        synonyms=(
            ("cellar", "basement"), ("crawl", "crawl_space"), ("on a slab", "slab"),
            ("concrete pad", "slab"), ("piers", "pier_and_beam"), ("stilts", "pier_and_beam"),
        ),
    ),
    Field(
        "basement_finished",
        "property",
        "Is the basement finished?",
        AnswerType.BOOL,
        asked_when=Condition("foundation_type", "eq", "basement"),
    ),
    Field(
        "garage_type",
        "property",
        "Is there a garage, and is it attached?",
        AnswerType.ENUM,
        choices=("attached", "detached", "carport", "none"),
        synonyms=(
            ("built in", "attached"), ("under the house", "attached"),
            ("separate", "detached"), ("out the back", "detached"),
            ("no garage", "none"), ("just a driveway", "none"),
        ),
    ),
    Field(
        "full_bathrooms",
        "property",
        "How many full bathrooms?",
        AnswerType.INT,
        minimum=0,
        maximum=12,
    ),
    Field(
        "half_bathrooms",
        "property",
        "And half baths?",
        AnswerType.INT,
        minimum=0,
        maximum=12,
    ),
    Field(
        "renovated_since_purchase",
        "property",
        "Has any major work been done since you bought it?",
        AnswerType.BOOL,
    ),
    Field(
        "renovation_year",
        "property",
        "What year was that work finished?",
        AnswerType.YEAR,
        minimum=1900,
        maximum=2030,
        asked_when=Condition("renovated_since_purchase", "eq", True),
    ),
    Field(
        "renovation_scope",
        "property",
        "What did the work cover?",
        AnswerType.STRING,
        asked_when=Condition("renovated_since_purchase", "eq", True),
    ),
)

_ROOF_SYSTEMS = (
    Field(
        "roof_age_years",
        "roof_systems",
        "How old is the roof?",
        AnswerType.INT,
        reprompts=("Any idea when the roof was last done? A rough number of years is fine.",),
        minimum=0,
        maximum=120,
        required_for_quote=True,
        feeds_rules=("roof_too_old_asphalt", "roof_too_old_other", "roof_ageing"),
    ),
    Field(
        "roof_material",
        "roof_systems",
        "What is the roof covered with, asphalt shingle, metal, tile?",
        AnswerType.ENUM,
        choices=("asphalt_shingle", "architectural_shingle", "metal", "tile", "slate", "wood_shake", "flat_membrane"),
        synonyms=(
            ("architectural", "architectural_shingle"), ("dimensional", "architectural_shingle"),
            ("three tab", "asphalt_shingle"), ("asphalt", "asphalt_shingle"),
            ("composition", "asphalt_shingle"), ("regular shingle", "asphalt_shingle"),
            ("standing seam", "metal"), ("tin", "metal"), ("steel", "metal"),
            ("clay", "tile"), ("concrete tile", "tile"), ("terracotta", "tile"),
            ("cedar shake", "wood_shake"), ("shake", "wood_shake"),
            ("rubber", "flat_membrane"), ("epdm", "flat_membrane"), ("tpo", "flat_membrane"),
        ),
        required_for_quote=True,
        feeds_rules=("roof_too_old_asphalt", "roof_too_old_other", "wood_shake_roof"),
    ),
    Field(
        "roof_shape",
        "roof_systems",
        "Is it a pitched roof or flat?",
        AnswerType.ENUM,
        choices=("gable", "hip", "flat", "mansard", "mixed"),
    ),
    Field(
        "roof_replaced_after_claim",
        "roof_systems",
        "Was that replacement done through an insurance claim?",
        AnswerType.BOOL,
        asked_when=Condition("roof_age_years", "lte", 10),
    ),
    Field(
        "electrical_update_year",
        "roof_systems",
        "When was the electrical work last updated?",
        AnswerType.YEAR,
        minimum=1900,
        maximum=2030,
        feeds_rules=("old_home_no_updates",),
    ),
    Field(
        "electrical_knob_and_tube",
        "roof_systems",
        "Is there any of the old knob and tube wiring still in use?",
        AnswerType.BOOL,
        asked_when=Condition("year_built", "lt", 1960),
        feeds_rules=("knob_and_tube_wiring",),
    ),
    Field(
        "electrical_panel_amps",
        "roof_systems",
        "Do you know the amperage of the panel?",
        AnswerType.INT,
        minimum=30,
        maximum=800,
        asked_when=Condition("year_built", "lt", 1990),
    ),
    Field(
        "plumbing_update_year",
        "roof_systems",
        "And the plumbing, when was that last done?",
        AnswerType.YEAR,
        minimum=1900,
        maximum=2030,
        feeds_rules=("old_home_no_updates",),
    ),
    Field(
        "plumbing_material",
        "roof_systems",
        "Do you know what the supply pipes are, copper, PEX, or galvanised?",
        AnswerType.ENUM,
        choices=("copper", "pex", "cpvc", "galvanised", "polybutylene", "unknown"),
        synonyms=(
            ("plastic", "pex"), ("grey plastic", "polybutylene"), ("gray plastic", "polybutylene"),
            ("poly", "polybutylene"), ("galvanized", "galvanised"), ("iron", "galvanised"),
            ("no idea", "unknown"), ("not sure", "unknown"),
        ),
        feeds_rules=("polybutylene_plumbing",),
    ),
    Field(
        "heating_type",
        "roof_systems",
        "How is the house heated?",
        AnswerType.ENUM,
        choices=("gas_forced_air", "electric", "heat_pump", "oil", "propane", "boiler", "other"),
        synonyms=(
            ("forced air", "gas_forced_air"), ("gas furnace", "gas_forced_air"), ("gas", "gas_forced_air"),
            ("baseboard", "electric"), ("electric", "electric"),
            ("pump", "heat_pump"), ("mini split", "heat_pump"),
            ("oil", "oil"), ("kerosene", "oil"), ("propane", "propane"), ("lpg", "propane"),
            ("radiators", "boiler"), ("hot water", "boiler"), ("steam", "boiler"),
        ),
    ),
    Field(
        "oil_tank_location",
        "roof_systems",
        "Is the oil tank above ground or buried?",
        AnswerType.ENUM,
        choices=("above_ground", "underground", "basement"),
        asked_when=Condition("heating_type", "eq", "oil"),
        feeds_rules=("buried_oil_tank",),
    ),
    Field(
        "secondary_heat",
        "roof_systems",
        "Is there a wood stove, pellet stove or anything like that as a second heat source?",
        AnswerType.ENUM,
        choices=("none", "wood_stove", "pellet_stove", "fireplace_insert", "space_heater"),
        synonyms=(
            ("nothing", "none"), ("no", "none"), ("just the furnace", "none"),
            ("log burner", "wood_stove"), ("wood burner", "wood_stove"), ("woodstove", "wood_stove"),
            ("pellet", "pellet_stove"), ("insert", "fireplace_insert"),
            ("open fire", "fireplace_insert"), ("plug in heater", "space_heater"),
        ),
        feeds_rules=("wood_stove_uninspected",),
    ),
    Field(
        "wood_stove_professionally_installed",
        "roof_systems",
        "Was that put in professionally?",
        AnswerType.BOOL,
        asked_when=Condition("secondary_heat", "in", ("wood_stove", "pellet_stove", "fireplace_insert")),
    ),
    Field(
        "wood_stove_inspected",
        "roof_systems",
        "Has it been inspected or swept in the last year?",
        AnswerType.BOOL,
        asked_when=Condition("secondary_heat", "in", ("wood_stove", "pellet_stove", "fireplace_insert")),
        feeds_rules=("wood_stove_uninspected",),
    ),
)

_PROTECTIVE = (
    Field(
        "smoke_detectors",
        "protective_risk",
        "Are there working smoke detectors through the house?",
        AnswerType.BOOL,
    ),
    Field(
        "monitored_alarm",
        "protective_risk",
        "Is there a burglar alarm that is monitored by a company?",
        AnswerType.BOOL,
    ),
    Field(
        "alarm_type",
        "protective_risk",
        "Is that monitoring for burglary, fire, or both?",
        AnswerType.ENUM,
        choices=("burglary", "fire", "both"),
        asked_when=Condition("monitored_alarm", "eq", True),
    ),
    Field(
        "sprinkler_system",
        "protective_risk",
        "Any sprinkler system inside?",
        AnswerType.BOOL,
    ),
    Field(
        "hydrant_distance_feet",
        "protective_risk",
        "Roughly how far is the nearest fire hydrant, in feet?",
        AnswerType.INT,
        minimum=0,
        maximum=20000,
        feeds_rules=("far_from_protection",),
    ),
    Field(
        "fire_station_miles",
        "protective_risk",
        "And how many miles to the nearest fire station?",
        AnswerType.INT,
        minimum=0,
        maximum=200,
        feeds_rules=("far_from_protection",),
    ),
    Field(
        "pool",
        "protective_risk",
        "Is there a swimming pool?",
        AnswerType.BOOL,
    ),
    Field(
        "pool_fenced",
        "protective_risk",
        "Is the pool fenced, with a gate that latches?",
        AnswerType.BOOL,
        asked_when=Condition("pool", "eq", True),
        feeds_rules=("unfenced_pool",),
    ),
    Field(
        "pool_diving_board",
        "protective_risk",
        "Is there a diving board or a slide?",
        AnswerType.BOOL,
        asked_when=Condition("pool", "eq", True),
        feeds_rules=("pool_diving_board_present",),
    ),
    Field(
        "trampoline",
        "protective_risk",
        "Is there a trampoline on the property?",
        AnswerType.BOOL,
        feeds_rules=("trampoline_present",),
    ),
    Field(
        "dogs",
        "protective_risk",
        "Any dogs at the property?",
        AnswerType.BOOL,
    ),
    Field(
        "dog_breed",
        "protective_risk",
        "What breed?",
        AnswerType.STRING,
        asked_when=Condition("dogs", "eq", True),
        feeds_rules=("restricted_dog_breed",),
    ),
    Field(
        "dog_bite_history",
        "protective_risk",
        "Has there ever been a bite or an injury reported?",
        AnswerType.BOOL,
        asked_when=Condition("dogs", "eq", True),
        feeds_rules=("dog_bite_history",),
    ),
    Field(
        "business_at_home",
        "protective_risk",
        "Is any business run from the house?",
        AnswerType.BOOL,
    ),
    Field(
        "business_type",
        "protective_risk",
        "What sort of business is it?",
        AnswerType.STRING,
        asked_when=Condition("business_at_home", "eq", True),
    ),
    Field(
        "business_employees_onsite",
        "protective_risk",
        "How many people work there on site?",
        AnswerType.INT,
        minimum=0,
        maximum=200,
        asked_when=Condition("business_at_home", "eq", True),
        feeds_rules=("commercial_exposure",),
    ),
    Field(
        "business_client_visits",
        "protective_risk",
        "Do customers come to the property?",
        AnswerType.BOOL,
        asked_when=Condition("business_at_home", "eq", True),
        feeds_rules=("commercial_exposure",),
    ),
    Field(
        "solar_panels",
        "protective_risk",
        "Are there solar panels?",
        AnswerType.BOOL,
    ),
    Field(
        "solar_ownership",
        "protective_risk",
        "Are those owned outright or leased?",
        AnswerType.ENUM,
        choices=("owned", "leased", "ppa"),
        synonyms=(
            ("we bought them", "owned"), ("paid for", "owned"), ("outright", "owned"),
            ("lease", "leased"), ("rented", "leased"),
            ("power purchase", "ppa"), ("buy the power", "ppa"),
        ),
        asked_when=Condition("solar_panels", "eq", True),
    ),
)

_COVERAGE = (
    Field(
        "currently_insured",
        "coverage_policy",
        "Do you have home insurance in place right now?",
        AnswerType.BOOL,
        required_for_quote=True,
        feeds_rules=("coverage_lapse",),
    ),
    Field(
        "current_carrier_known",
        "coverage_policy",
        "Do you know who it is with?",
        AnswerType.BOOL,
        asked_when=Condition("currently_insured", "eq", True),
    ),
    Field(
        "current_premium_annual",
        "coverage_policy",
        "What are you paying a year at the moment?",
        AnswerType.CURRENCY,
        reprompts=("Even a rough annual figure helps me tell you whether we can beat it.",),
        minimum=0,
        maximum=200000,
        asked_when=Condition("currently_insured", "eq", True),
    ),
    Field(
        "current_dwelling_coverage",
        "coverage_policy",
        "How much is the house itself insured for?",
        AnswerType.CURRENCY,
        minimum=0,
        maximum=20000000,
        asked_when=Condition("currently_insured", "eq", True),
        feeds_rules=("dwelling_coverage_low",),
    ),
    Field(
        "desired_deductible",
        "coverage_policy",
        "What deductible would you like me to quote, five hundred, a thousand, or higher?",
        AnswerType.ENUM,
        choices=("500", "1000", "2500", "5000", "other"),
        synonyms=(
            ("five hundred", "500"), ("a thousand", "1000"), ("one thousand", "1000"),
            ("twenty five hundred", "2500"), ("five thousand", "5000"),
            ("whatever is cheapest", "other"), ("not sure", "other"),
        ),
    ),
    Field(
        "escrow_pays_premium",
        "coverage_policy",
        "Does your mortgage escrow pay the premium, or do you pay it directly?",
        AnswerType.BOOL,
    ),
    Field(
        "policy_expiry_date",
        "coverage_policy",
        "When does the current policy renew?",
        AnswerType.DATE,
        asked_when=Condition("currently_insured", "eq", True),
    ),
    Field(
        "coverage_lapse_days",
        "coverage_policy",
        "How long has it been without cover?",
        AnswerType.INT,
        minimum=0,
        maximum=10000,
        asked_when=Condition("currently_insured", "eq", False),
        feeds_rules=("coverage_lapse",),
    ),
    Field(
        "lender_partner_reference",
        "coverage_policy",
        "Do you have the reference your lender gave you?",
        AnswerType.STRING,
    ),
)

_LOSS_HISTORY = (
    Field(
        "claims_last_five_years",
        "loss_history",
        "Have you claimed on your home insurance in the last five years?",
        AnswerType.BOOL,
        required_for_quote=True,
        feeds_rules=("too_many_claims",),
    ),
    Field(
        "claims_count",
        "loss_history",
        "How many claims was that?",
        AnswerType.INT,
        minimum=0,
        maximum=20,
        asked_when=Condition("claims_last_five_years", "eq", True),
        feeds_rules=("too_many_claims", "claims_moderate"),
    ),
    Field(
        "claim_year",
        "loss_history",
        "What year was that one?",
        AnswerType.YEAR,
        minimum=1990,
        maximum=2030,
        repeat_group="claims",
    ),
    Field(
        "claim_type",
        "loss_history",
        "What was it for?",
        AnswerType.ENUM,
        choices=("water", "wind_hail", "fire", "theft", "liability", "other"),
        synonyms=(
            ("burst pipe", "water"), ("leak", "water"), ("flood", "water"), ("water damage", "water"),
            ("hail", "wind_hail"), ("storm", "wind_hail"), ("wind", "wind_hail"), ("tree", "wind_hail"),
            ("fire", "fire"), ("smoke", "fire"),
            ("break in", "theft"), ("burglary", "theft"), ("stolen", "theft"),
            ("dog bite", "liability"), ("someone was hurt", "liability"), ("injury", "liability"),
        ),
        repeat_group="claims",
        feeds_rules=("repeat_water_claims",),
    ),
    Field(
        "claim_amount_paid",
        "loss_history",
        "Roughly how much did they pay out?",
        AnswerType.CURRENCY,
        minimum=0,
        maximum=5000000,
        repeat_group="claims",
    ),
    Field(
        "claim_repaired",
        "loss_history",
        "Has all the damage been repaired?",
        AnswerType.BOOL,
        repeat_group="claims",
        # Only worth asking where money actually changed hands. A denied or withdrawn claim has
        # nothing to repair.
        asked_when=Condition("claim_amount_paid#{i}", "gt", 0),
        feeds_rules=("unrepaired_damage",),
    ),
    Field(
        "prior_cancellation",
        "loss_history",
        "Has a carrier ever cancelled or declined to renew a policy of yours?",
        AnswerType.BOOL,
        required_for_quote=True,
        feeds_rules=("cancelled_for_non_payment", "prior_cancellation_other"),
    ),
    Field(
        "cancellation_reason",
        "loss_history",
        "Do you know why?",
        AnswerType.ENUM,
        choices=("non_payment", "claims", "underwriting", "moved", "other", "unknown"),
        synonyms=(
            ("missed a payment", "non_payment"), ("did not pay", "non_payment"),
            ("didn't pay", "non_payment"), ("late", "non_payment"),
            ("too many claims", "claims"), ("claims", "claims"),
            ("inspection", "underwriting"), ("the roof", "underwriting"),
            ("moved", "moved"), ("sold", "moved"),
            ("no idea", "unknown"), ("they never said", "unknown"),
        ),
        asked_when=Condition("prior_cancellation", "eq", True),
        feeds_rules=("cancelled_for_non_payment", "prior_cancellation_other"),
    ),
)

_AUTO = (
    Field(
        "bundle_interest",
        "auto_bundle",
        "Would you like me to look at the car insurance at the same time? It is usually where the bigger saving is.",
        AnswerType.BOOL,
        required_for_quote=True,
    ),
    Field(
        "vehicle_count",
        "auto_bundle",
        "How many vehicles would that cover?",
        AnswerType.INT,
        minimum=0,
        maximum=8,
        asked_when=Condition("bundle_interest", "eq", True),
    ),
    Field(
        "vehicle_year",
        "auto_bundle",
        "What year is it?",
        AnswerType.YEAR,
        minimum=1950,
        maximum=2030,
        repeat_group="vehicles",
    ),
    Field(
        "vehicle_make_model",
        "auto_bundle",
        "Make and model?",
        AnswerType.STRING,
        repeat_group="vehicles",
    ),
    Field(
        "vehicle_ownership",
        "auto_bundle",
        "Is it owned outright, financed, or leased?",
        AnswerType.ENUM,
        choices=("owned", "financed", "leased"),
        synonyms=(
            ("paid off", "owned"), ("outright", "owned"), ("mine", "owned"),
            ("on finance", "financed"), ("loan", "financed"), ("paying it off", "financed"),
            ("lease", "leased"),
        ),
        repeat_group="vehicles",
    ),
    Field(
        "vehicle_annual_miles",
        "auto_bundle",
        "Roughly how many miles a year?",
        AnswerType.INT,
        minimum=0,
        maximum=200000,
        repeat_group="vehicles",
    ),
    Field(
        "driver_count",
        "auto_bundle",
        "And how many drivers in the household?",
        AnswerType.INT,
        minimum=0,
        maximum=8,
        asked_when=Condition("bundle_interest", "eq", True),
    ),
    Field(
        "driver_licence_status",
        "auto_bundle",
        "Is their licence current?",
        AnswerType.ENUM,
        choices=("valid", "permit", "suspended", "expired", "none"),
        synonyms=(
            ("full licence", "valid"), ("full license", "valid"), ("yes", "valid"), ("current", "valid"),
            ("learner", "permit"), ("provisional", "permit"),
            ("suspended", "suspended"), ("banned", "suspended"), ("taken away", "suspended"),
            ("expired", "expired"), ("out of date", "expired"),
            ("does not drive", "none"), ("no licence", "none"), ("no license", "none"),
        ),
        repeat_group="drivers",
        feeds_rules=("suspended_licence",),
    ),
    Field(
        "driver_years_licensed",
        "auto_bundle",
        "How many years have they been driving?",
        AnswerType.INT,
        minimum=0,
        maximum=80,
        repeat_group="drivers",
    ),
    Field(
        "driver_incidents_three_years",
        "auto_bundle",
        "Any accidents or tickets in the last three years?",
        AnswerType.INT,
        minimum=0,
        maximum=20,
        repeat_group="drivers",
        feeds_rules=("driver_incidents_high",),
    ),
)

_DISPOSITION = (
    Field(
        "wants_agent_now",
        "disposition",
        "I can put you through to a licensed agent now to go over the numbers. Would you like that?",
        AnswerType.BOOL,
    ),
    Field(
        "callback_window",
        "disposition",
        "When suits you for a call back?",
        AnswerType.ENUM,
        choices=("weekday_morning", "weekday_afternoon", "weekday_evening", "saturday", "no_preference"),
        synonyms=(
            ("morning", "weekday_morning"), ("before lunch", "weekday_morning"),
            ("afternoon", "weekday_afternoon"), ("after lunch", "weekday_afternoon"),
            ("evening", "weekday_evening"), ("after work", "weekday_evening"),
            ("saturday", "saturday"), ("weekend", "saturday"),
            ("any time", "no_preference"), ("whenever", "no_preference"),
        ),
        asked_when=Condition("wants_agent_now", "eq", False),
    ),
    Field(
        "quote_email",
        "disposition",
        "What email should the quotes go to?",
        AnswerType.EMAIL,
    ),
    Field(
        "email_permission",
        "disposition",
        "Happy for us to email you the comparison?",
        AnswerType.BOOL,
    ),
    Field(
        "additional_notes",
        "disposition",
        "Anything else about the property I should pass on?",
        AnswerType.STRING,
    ),
)

INTAKE = Questionnaire(
    name="home_quote_intake",
    version="3.2",
    sections=SECTIONS,
    fields=_IDENTITY + _PROPERTY + _ROOF_SYSTEMS + _PROTECTIVE + _COVERAGE + _LOSS_HISTORY + _AUTO + _DISPOSITION,
    repeat_groups=REPEAT_GROUPS,
    opening=(
        "Hello, this is Avery calling from Alderway Insurance Services on a recorded line. "
        "Your lender asked us to shop your home insurance before closing."
    ),
    closing=(
        "That is everything I need. Thank you for your time."
    ),
)

__all__ = ["INTAKE", "LICENSED_STATES", "REPEAT_GROUPS", "RESTRICTED_DOG_BREEDS", "SECTIONS"]
